import json
import os
from datetime import datetime

def generate_html_dashboard():
    # 查找最新的分析结果文件
    data_dir = "social-intelligence-mvp/data/"
    processed_files = [f for f in os.listdir(data_dir) if f.startswith("processed_news_") or f.startswith("raw_news_")]
    if not processed_files:
        return "No data files found."
    
    latest_file = os.path.join(data_dir, sorted(processed_files)[-1])
    
    with open(latest_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # 简单的 HTML 模板
    html_content = f"""
    <!DOCTYPE html>
    <html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Social Intelligence MVP Dashboard</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            .sentiment-positive {{ border-left: 6px solid #10b981; }}
            .sentiment-negative {{ border-left: 6px solid #ef4444; }}
            .sentiment-neutral {{ border-left: 6px solid #6b7280; }}
        </style>
    </head>
    <body class="bg-gray-100 font-sans leading-normal tracking-normal">
        <div class="container mx-auto p-6">
            <header class="mb-10 text-center">
                <h1 class="text-4xl font-extrabold text-gray-800">🚀 Social Intelligence MVP</h1>
                <p class="text-gray-600 mt-2">实时品牌舆情监控仪表盘 | 最后更新: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </header>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
    """

    for item in data:
        # 模拟情感判断（如果还没有经过 AI 处理，这里做个简单示例）
        sentiment = item.get('sentiment', 'neutral')
        sentiment_class = f"sentiment-{sentiment}"
        
        # 风险标注
        risk_tag = ""
        if sentiment == 'negative':
            risk_tag = '<span class="bg-red-100 text-red-800 text-xs font-medium px-2.5 py-0.5 rounded ml-2">⚠️ 风险预警</span>'

        html_content += f"""
                <div class="bg-white rounded-lg shadow-md p-6 {sentiment_class}">
                    <div class="flex justify-between items-start">
                        <span class="inline-block px-3 py-1 text-sm font-semibold text-blue-700 bg-blue-100 rounded-full">
                            {item.get('keyword', '未知')}
                        </span>
                        <span class="text-xs text-gray-400">{item.get('published', '')}</span>
                    </div>
                    <h2 class="text-xl font-bold mt-3 text-gray-800 leading-tight">
                        <a href="{item.get('link', '#')}" target="_blank" class="hover:text-blue-500 transition-colors">
                            {item.get('title', '无标题')}
                        </a>
                        {risk_tag}
                    </h2>
                    <p class="text-gray-500 text-sm mt-4 italic">来源: {item.get('source', '网络')}</p>
                </div>
        """

    html_content += """
            </div>
            
            <footer class="mt-12 text-center text-gray-400 text-sm">
                Generated by Eric Agent | OpenClaw Workspace
            </footer>
        </div>
    </body>
    </html>
    """
    
    output_path = "social-intelligence-mvp/index.html"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    return output_path

if __name__ == "__main__":
    path = generate_html_dashboard()
    print(f"Dashboard generated at: {path}")
